---
date: 2020-06-03
title: Continuous Learning in a Time of Continuous Change
venue: Statistical Society of Canada Conference, virtual
---

It’s a universally accepted truism that we live in a time of unprecedented change, both in terms of the magnitude and the pace of those changes. In the world of statistics, there have been enormous changes at the intersection of tools, methodologies and techniques, and transparency. New software packages, new ways to analyze data, and new open data arrive every day, each of which have implications for how we approach our professional development. In this talk, I will present observations drawn from applied statistical practice and teaching mid-career professionals that suggest possible responses that will allow us to keep pace with a perpetually shifting ecosystem.

**L’apprentissage continu en période de changement permanent**

C’est un truisme universellement accepté que de dire que nous vivons une époque de changements sans précédent, tant en termes d’ampleur que de rythme de ces changements. Dans le monde des statistiques, les outils, les méthodologies, les techniques et la transparence ont connu d’énormes changements. De nouveaux logiciels, de nouvelles méthodes d’analyse des données et de nouvelles données ouvertes arrivent chaque jour, chacun ayant des implications sur la manière dont nous abordons notre développement professionnel. Dans cet exposé, je présenterai des observations tirées de la pratique de la statistique appliquée et de l’enseignement à des professionnels en milieu de carrière qui suggèrent des réponses possibles qui nous permettront de suivre le rythme d’un écosystème en perpétuelle évolution.

## Long-form article

[_Continuous Learning in a Time of Continuous Change_](../post/2022-06-03_ssc_learning/)

