# Data Analytics Coding Fundamentals (DAMS302)

Data Analytics Coding Fundamentals (DAMS302) is part of the [Data Analytics for Management Science](https://continuingstudies.uvic.ca/data-computing-and-technology/programs/data-analytics-for-management-science) diploma program at the University of Victoria's [Division of Continuing Studies (DCS)](https://continuingstudies.uvic.ca/).

The course registration page: [Data Analytics Coding Fundamentals](https://continuingstudies.uvic.ca/data-computing-and-technology/courses/data-analytics-coding-fundamentals)

The [Data Analytics Coding Fundamentals (DAMS302) course book](https://bookdown.org/martin_monkman/DataAnalyticsCodingFundamentals/)

* * *

# Data Analytics Provisioning, Importing, Extracting and Manipulation (DAMS405)

Data Analytics Provisioning, Importing, Extracting and Manipulation (DAMS405) is part of the [Data Analytics for Management Science](https://continuingstudies.uvic.ca/data-computing-and-technology/programs/data-analytics-for-management-science) diploma program at the University of Victoria's [Division of Continuing Studies (DCS)](https://continuingstudies.uvic.ca/).


The course registration page: [Data Analytics Provisioning, Importing, Extracting and Manipulation](https://continuingstudies.uvic.ca/data-computing-and-technology/courses/data-provisioning-importing-extracting-and-manipulation)
